language: android
android:
  components:
    - android-27

jdk:
  - oraclejdk8

script:
  - ./gradlew clean check lint test

env:
  global:
    - GRADLE_OPTS="-Xmx2048m -XX:MaxPermSize=1024m"

branches:
  except:
    - gh-pages

notifications:
  email: false

sudo: false
